Add `threadStatus` to IOSim and IOSimPOR
input-output-hk/io-sim pull request #19
Opened 2022-08-31 07:58 UTC by MaximilianAlgehed

This PR introduces an implementation of `threadStatus` for `IOSim`. It's currently a bit fast and loose on the "blocked reason" for threads (e.g. reading `MVar`s etc.) but should implement the rest of the functionality faithfully.

2022-09-01 07:59 UTC, MaximilianAlgehed commented
@coot do you perhaps have time to review this?

2022-09-01 16:13 UTC, coot requested changes
@MaximilianAlgehed thanks that looks good.  I see one problem with this implementation: it does not work well with our implementation of `MVar`'s which is based on `TVar`'s.  When a thread is blocked on an `MVar` we will thus report `ThreadBlocked BlockedOnSTM`. But it shouldn't be difficult to distinguished `MVar`s and `TVar`s.  We's need  to add a boolean flag to `TVar`: `tvarIsMVar :: Bool`.  The problem to solve is how to update it when we create an `MVar` in [`newEmptyMVarDefault`](https://github.com/input-output-hk/io-sim/blob/main/io-classes/src/Control/Monad/Class/MonadMVar.hs#L171-L172).  The simplest way would be to move that function to `io-sim`, where we have access to `TVar` internals.

2022-09-01 16:13 UTC, coot commented on io-sim/test/Test/IOSim.hs
> +    ]
Let's try to fit into 80 columns:
 
```suggestion
    [ testProperty "thread status finished (IOSim)"
    $ withMaxSuccess 1 $ runSimOrThrow prop_thread_status_finished
    , testProperty "thread status finished (IO)"
    $ withMaxSuccess 1 $ ioProperty    prop_thread_status_finished
    , testProperty "thread status running (IOSim)"
    $ withMaxSuccess 1 $ runSimOrThrow prop_thread_status_running
    , testProperty "thread status running (IO)"
    $ withMaxSuccess 1 $ ioProperty    prop_thread_status_running
    , testProperty "thread status blocked (IOSim)"
    $ withMaxSuccess 1 $ runSimOrThrow prop_thread_status_blocked
    , testProperty "thread status blocked (IO)"
    $ withMaxSuccess 1 $ ioProperty    prop_thread_status_blocked
    , testProperty "thread status blocked delay (IOSim)"
    $ wi1 $ runSimOrThrow prop_thread_status_blocked_delay
    , testProperty "thread status blocked delay (IO)"
    $ withMaxSuccess 1 $ ioProperty    prop_thread_status_blocked_delay
    , testProperty "thread status died (IOSim)"
    $ withMaxSuccess 1 $ runSimOrThrow prop_thread_status_died
    , testProperty "thread status died (IO)"
    $ withMaxSuccess 1 $ ioProperty    prop_thread_status_died
    , testProperty "thread status died_own (IOSim)"
    $ withMaxSuccess 1 $ runSimOrThrow prop_thread_status_died_own
    , testProperty "thread status died_own (IO)"
    $ withMaxSuccess 1 $ ioProperty    prop_thread_status_died_own
    , testProperty "thread status yield (IOSim)"
    $ withMaxSuccess 1 $ runSimOrThrow prop_thread_status_yield
    , testProperty "thread status yield (IO)"
    $ withMaxSuccess 1 $ ioProperty    prop_thread_status_yield
    , testProperty "thread status mask (IOSim)"
    $ withMaxSuccess 1 $ runSimOrThrow prop_thread_status_mask
    , testProperty "thread status mask (IO)"
    $ withMaxSuccess 1 $ ioProperty    prop_thread_status_mask
    , testProperty "thread status mask blocked (IOSim)"
    $ w1 $ runSimOrThrow prop_thread_status_mask_blocked
    , testProperty "thread status mask blocked (IO)"
    $ withMaxSuccess 1 $ ioProperty    prop_thread_status_mask_blocked
    ]

```

2022-09-01 16:13 UTC, coot commented on io-sim/test/Test/IOSim.hs
> +prop_two_threads_expect_ target prop = prop_two_threads_expect target (const $ yield) prop
```suggestion
prop_two_threads_expect_ target prop =
  prop_two_threads_expect target (const $ yield) prop
```

2022-09-01 16:13 UTC, coot commented on io-sim/test/Test/IOSim.hs
> +prop_thread_status_finished :: (MonadFork m, MonadDelay m, MonadThread m) => m Property
Could you also try to fit the other type signatures into 80 columns?
```suggestion
prop_thread_status_finished :: (MonadFork m, MonadDelay m, MonadThread m)
                            => m Property
```

2022-09-01 16:13 UTC, coot commented on io-sim/test/Test/IOSim.hs
> +prop_thread_status_finished :: (MonadFork m, MonadDelay m, MonadThread m) => m Property
I need to link our [style guide](https://github.com/input-output-hk/ouroboros-network/blob/master/docs/StyleGuide.md) in this repo.

2022-09-02 07:55 UTC, MaximilianAlgehed commented on io-sim/src/Control/Monad/IOSimPOR/Internal.hs
> +                               , threadEffect = effect }
This is probably just a left-over from experimenting that I missed when going over the diff.

2022-09-02 07:57 UTC, MaximilianAlgehed commented on io-sim/src/Control/Monad/IOSim/Internal.hs
> +{-# LANGUAGE RecordWildCards            #-}
Yes, got rid of it.

2022-09-02 07:59 UTC, MaximilianAlgehed commented on io-sim/src/Control/Monad/IOSimPOR/Internal.hs
> +    threadDone    :: !Bool, -- TODO: do we need this when we keep track of finished threads separately?
I realized when going over the code with John. Perhaps a welcome optimization would be to put the `FinishedReason` in here too then - to aovoid that look-up as well.

2022-09-02 08:19 UTC, MaximilianAlgehed commented
@coot do you think we should try to address the `BlockReason` issues in this PR or do we postpone that for later?

2022-09-03 09:24 UTC, coot commented
`BlockReason` could be addressed later; Please leave a comment which links to an issue.

2022-09-05 07:56 UTC, MaximilianAlgehed commented
Issue mentioning `BlockReason` https://github.com/input-output-hk/io-sim/issues/21.

2022-09-05 12:40 UTC, MaximilianAlgehed commented
@coot I think this should be about ready now.

2022-09-15 21:36 UTC, dcoutts reviewed
This looks ok to me.

I have to say I was not aware of the semantics of `threadStatus`. It looks like you believe that the difference between status died and finished is receiving an async exception.

The library docs merely say
```
ThreadFinished | the thread has finished
ThreadDied | the thread received an uncaught exception
```
without saying anything about async vs sync exceptions.

My own experiment is even less helpful, it suggests that `ThreadDied` isn't used at all!
```
import GHC.Conc
import Control.Exception

main = do
  --setUncaughtExceptionHandler throwIO

  tid <- forkIO $ do
           print "foo"
           threadDelay 10000000 --10sec
           print "bar"

  print =<< threadStatus tid
  throwTo tid (ErrorCall "oh noes")
  threadDelay 1000000
  print =<< threadStatus tid
```
and
```
 ghc-8.10.7 ThreadStatus.hs 
[1 of 1] Compiling Main             ( ThreadStatus.hs, ThreadStatus.o )
Linking ThreadStatus ...
[duncan@dunky io-sim]$ ./ThreadStatus 
ThreadRunning
ThreadStatus: oh noes
ThreadFinished
```
I thought it might be related to the default top-level exception handler for forkIO threads, but apparently not. If one uncomments the line `setUncaughtExceptionHandler throwIO` then the final result is instead
```
$ ./ThreadStatus 
ThreadRunning
ThreadRunning
```

I cannot get ghc to ever report `ThreadDied`.

If we don't need to track async vs sync exceptions for the cause here, then it'd simplify the patch quite a bit. If it were just threads terminating with an exception (any, sync or async) vs terminating via `return` then we'd not have to track so much in this patch.

2022-09-16 06:31 UTC, MaximilianAlgehed commented on io-sim/test/Main.hs
> +  -- , Test.Control.Monad.Class.MonadMVar.tests
Whoops, I think we turned these off because they were flaky but not for any reason that we could see related to anything we did. @dcoutts any clue?

2022-09-16 06:33 UTC, MaximilianAlgehed commented
@dcoutts did you check the tests? On my machine the tests pass - indicating that our hypothesis about the difference between synch and asynch exceptions is true *at least some of the time*.  See specifically the test
[prop_thread_status_died](https://github.com/input-output-hk/io-sim/pull/19/files#diff-843938f4a3c358e946651fcd9a6166fdb1cb567815fb8dfdbeae86f3a41c66cdR254-R263). Could you check out the tests and run them on your machine to see if they match?

2022-09-16 06:35 UTC, MaximilianAlgehed commented
And to be clear, we were *very surprised* by the semantics we observed!

2022-09-20 09:27 UTC, MaximilianAlgehed commented
@coot or @dcoutts do you mind running the CI here so we can get things to turn green?

2022-09-22 09:29 UTC, coot approved these changes
LGTM

2022-09-22 09:32 UTC, coot commented
I don't see how to make CI run, there's no box which [github docs](https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks) mentions :disappointed:.

2022-09-28 12:15 UTC, MaximilianAlgehed commented
@dcoutts could you perhaps push the right buttons on this so we can get it merged?

2022-09-28 14:25 UTC, coot commented
> @dcoutts could you perhaps push the right buttons on this so we can get it merged?

I asked similar question today.

Could you rebase the branch on top of `origin/main`: even if we run the workflows now they will fail without rebase (I checked that locally).

2022-09-28 15:46 UTC, coot commented
@MaximilianAlgehed I pushed PR #27 with your changes (rebased), unfortunately two tests failed:
```
       thread status died_own (IO):             FAIL
        *** Failed! Falsified (after 1 test):
        ThreadFinished /= ThreadBlocked BlockedOnMVar
        Use --quickcheck-replay=392463 to reproduce.
        Use -p '/thread status died_own (IO)/' to rerun this test only.

       thread status mask (IO):                 FAIL
        *** Failed! Falsified (after 1 test):
        ThreadFinished /= ThreadBlocked BlockedOnMVar
        Use --quickcheck-replay=499493 to reproduce.
        Use -p '/thread status mask (IO)/' to rerun this test only.

```

2022-09-29 07:27 UTC, MaximilianAlgehed commented
@coot that's a bit worrying - they pass locally. Are the tests run in parallel in CI? That might affect scheduling (these tests are understandably a bit sensitive to scheduling).

2022-09-29 08:53 UTC, coot commented
The problem is only on Windows, where I can reproduce it locally too.

2022-09-29 08:57 UTC, coot commented
Since `threadStatus` is not well specified, I think it's ok if we just disable these tests on Windows.

2022-09-29 08:59 UTC, MaximilianAlgehed commented
@coot That's fine with me. I'll make an issue that mentions this so I have something to come back to after the next spate of deadlines.

2022-09-29 09:06 UTC, MaximilianAlgehed commented
@coot I've made an issue here https://github.com/input-output-hk/io-sim/issues/28 and it's weirder than I thought! I finally got the time to look carefully at this and as I say in the issue the behaviour on Windows is probably just plain wrong! We don't do any operations that should put the thread that we ask `threadStatus` of in that state at any point in the execution!

2022-09-29 10:43 UTC, coot commented
Thanks, I disabled the tests in the other PR.  Once CI will finish I'll merge it.

2022-09-29 13:07 UTC, coot commented
Merged via #27.

2022-10-11 15:54 UTC, dcoutts commented
I've filed a GHC issue: https://gitlab.haskell.org/ghc/ghc/-/issues/22279

2022-10-13 16:11 UTC, coot commented
@dcoutts I created an issue to [track this](https://github.com/input-output-hk/io-sim/issues/38), let's close this PR as it's already merged via #27.

2022-10-13 16:11 UTC, closed without merging