Strict MVars without invariant checking
input-output-hk/io-sim pull request #72
Opened 2023-03-13 15:34 UTC by jorisdral

This PR provides a new `strict-mvar` packages that implements strict MVars without invariant checking. Strict MVars are implemented in a fairly straightforward way by wrapping lazy MVars and forcing evaluation to WHNF before placing values in the lazy MVar.

@dcoutts suggested that strict MVars with invariant checking should be provided separately from MVars without invariant checking. As such, this PR only provides the latter.

2023-03-13 15:44 UTC, jorisdral commented on strict-mvar/strict-mvar.cabal
> +description:         Strict MVars for `IO` and `io-sim`.
This should probably say `io-classes`

2023-03-13 15:44 UTC, jorisdral commented on strict-mvar/src/Control/Concurrent/Class/MonadMVar/Strict.hs
> +tryReadMVar = error "tryReadMVar: no lazy implementation exists"
Can be implemented after #70

2023-03-13 15:44 UTC, jorisdral commented on strict-mvar/strict-mvar.cabal
> +  location: https://github.com/input-output-hk/ouroboros-network
This is `s-r-p` is wrong

2023-03-28 14:46 UTC, coot requested changes
Very nice, just a few minor remarks.

2023-03-28 14:46 UTC, coot commented on strict-mvar/strict-mvar.cabal
> +                       io-classes  >= 0.3 && <0.5
we're about to publish `0.5`, so
```suggestion
                       io-classes  >= 0.3 && <0.6
```

2023-03-28 16:40 UTC, jorisdral commented on strict-mvar/strict-mvar.cabal
> +tested-with:         GHC == 8.10.7, GHC == 9.2.5, GHC == 9.4.3
Done. Also, `9.4.3` should have been `9.4.4`, so I've changed that

2023-03-28 16:44 UTC, jorisdral commented on strict-mvar/strict-mvar.cabal
> +description:         Strict MVars for `IO` and `io-sim`.
I've changed it to:

> Strict MVars for implementations of the `io-classes` MVar interface

2023-04-03 07:50 UTC, merged